/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.poli.regequipos.interfaz.menu;

import co.edu.poli.interfaz.equipos.GestionEquipos;
import co.edu.poli.regequipos.interfaz.marca.MarcaPpal;
import co.edu.poli.regequipos.interfaz.parametros.ParametrosPpal;
import co.edu.poli.regequipos.interfaz.persona.PersonaPpal;
import co.edu.poli.regequipos.interfaz.registro.RegistroPpal;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    RegistroPpal registroPpal;
    PersonaPpal personaPpal;
    ParametrosPpal parametrosPpal;
    MarcaPpal marcaPpal;
    GestionEquipos gestionEquipos;

    private static final String IMG_REGISTRO = "src/imagenes/registro.jpg";
    private static final String IMG_PERSONAS= "src/imagenes/personas.png";
    private static final String IMG_MARCAS= "src/imagenes/marcas.jpg";
    private static final String IMG_PARAMETROS= "src/imagenes/parametros.png";
    private static final String IMG_TIPO_EQUIPO= "src/imagenes/tiposEquipo.jpg";

    public Menu() {
        initComponents();

        try {
            BufferedImage img = ImageIO.read(new File(IMG_REGISTRO));
            ImageIcon icon = new ImageIcon(img);  
            icon.setDescription("Registro de equipos");            
            this.lblRegistro.setIcon(icon);
            //Imagen para Personas
            img = ImageIO.read(new File(IMG_PERSONAS));
            icon = new ImageIcon(img);  
            icon.setDescription("Registro de Personas");            
            this.lblPersonas.setIcon(icon);
            //Imagen para marcas            
            img = ImageIO.read(new File(IMG_MARCAS));
            icon = new ImageIcon(img);  
            icon.setDescription("Registro de Marcas");            
            this.lblMarcas.setIcon(icon);
            //Imagen para parámetros            
            img = ImageIO.read(new File(IMG_PARAMETROS));
            icon = new ImageIcon(img);  
            icon.setDescription("Registro de Parámetros");            
            this.lblParametros.setIcon(icon);
            //Imagen para tipos de equipos            
            img = ImageIO.read(new File(IMG_TIPO_EQUIPO));
            icon = new ImageIcon(img);  
            icon.setDescription("Registro de Tipos de Equipos");            
            this.lblTipoEquipo.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Ppal = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        lblPersonas = new javax.swing.JLabel();
        lblMarcas = new javax.swing.JLabel();
        lblParametros = new javax.swing.JLabel();
        lblTipoEquipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Ppal.setBackground(new java.awt.Color(255, 255, 255));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(26, 84, 147));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Menú de opciones");

        lblRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblRegistro.setPreferredSize(new java.awt.Dimension(80, 80));
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
        });

        lblPersonas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPersonas.setPreferredSize(new java.awt.Dimension(80, 80));
        lblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonasMouseClicked(evt);
            }
        });

        lblMarcas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblMarcas.setPreferredSize(new java.awt.Dimension(80, 80));
        lblMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMarcasMouseClicked(evt);
            }
        });

        lblParametros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblParametros.setPreferredSize(new java.awt.Dimension(80, 80));
        lblParametros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblParametrosMouseClicked(evt);
            }
        });

        lblTipoEquipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTipoEquipo.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 84, 147));
        jLabel1.setText("Ingreso de equipos");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 84, 147));
        jLabel2.setText("Gestion de personas");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 84, 147));
        jLabel3.setText("Gestion de marcas");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 84, 147));
        jLabel4.setText("Gestion de parametros");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 84, 147));
        jLabel5.setText("Tipos de equipos");

        javax.swing.GroupLayout pnl_PpalLayout = new javax.swing.GroupLayout(pnl_Ppal);
        pnl_Ppal.setLayout(pnl_PpalLayout);
        pnl_PpalLayout.setHorizontalGroup(
            pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PpalLayout.createSequentialGroup()
                .addGroup(pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_PpalLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(lblTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_PpalLayout.createSequentialGroup()
                        .addGroup(pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_PpalLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(lblPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_PpalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_PpalLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(pnl_PpalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(pnl_PpalLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_PpalLayout.setVerticalGroup(
            pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PpalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_titulo)
                .addGap(24, 24, 24)
                .addGroup(pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_PpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Ppal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Ppal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        try {
            registroPpal = new RegistroPpal();
            registroPpal.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error accediendo al formulario " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void lblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonasMouseClicked
        personaPpal = new PersonaPpal();
        this.setVisible(false);
        personaPpal.setVisible(true);
    }//GEN-LAST:event_lblPersonasMouseClicked

    private void lblMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcasMouseClicked
        marcaPpal = new MarcaPpal();
        marcaPpal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMarcasMouseClicked

    private void lblParametrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParametrosMouseClicked
        parametrosPpal = new ParametrosPpal();
        parametrosPpal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblParametrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMarcas;
    private javax.swing.JLabel lblParametros;
    private javax.swing.JLabel lblPersonas;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblTipoEquipo;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_Ppal;
    // End of variables declaration//GEN-END:variables
}
