/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.poli.regequipos.interfaz.parametros;

import co.edu.poli.regequipos.constantes.ConstantesApp;
import co.edu.poli.regequipos.entidades.Parametros;
import co.edu.poli.regequipos.interfaz.menu.Menu;
import co.edu.poli.regequipos.model.ParametrosModel;
import co.edu.polo.regequipos.dao.ParametrosDao;
import com.sun.javafx.css.Stylesheet;
import com.sun.javafx.css.parser.CSSParser;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;


import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ParametrosPpal extends javax.swing.JFrame {

    private ParametrosDao paramDao;
    

    public ParametrosPpal() {
        try {
            paramDao = new ParametrosDao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        this.refrescarTabla();
        try {
            BufferedImage img = ImageIO.read(new File(ConstantesApp.IMG_PATH));
            ImageIcon icon = new ImageIcon(img);
            this.lblHome.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        /*
        Estilos
        */
        //this.pnl_ppal.setBackground(Color.decode("#AFBFDA"));
    }

    public void refrescarTabla() {
        try {
            List<Parametros> lstParam = paramDao.consultaParametros(null, null, null);
            ParametrosModel model = new ParametrosModel(lstParam);
            this.tbl_Parametros.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(),
                    " Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ppal = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_idParam = new javax.swing.JLabel();
        txt_IdFiltro = new javax.swing.JTextField();
        lbl_valParam = new javax.swing.JLabel();
        txt_ValorFiltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_DescFiltro = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Parametros = new javax.swing.JTable();
        btn_nuevoParametro = new javax.swing.JButton();
        btn_ModfParam = new javax.swing.JButton();
        btn_ElimParam = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_ppal.setBackground(new java.awt.Color(255, 255, 255));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Parámetros generales");

        lbl_idParam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_idParam.setText("Identificador parámetro:");

        txt_IdFiltro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_IdFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdFiltroActionPerformed(evt);
            }
        });

        lbl_valParam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_valParam.setText("Valor parámetro:");

        txt_ValorFiltro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Descripción parámetro:");

        txt_DescFiltro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_DescFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DescFiltroActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(26, 84, 147));
        btn_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tbl_Parametros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_Parametros);

        btn_nuevoParametro.setBackground(new java.awt.Color(26, 84, 147));
        btn_nuevoParametro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_nuevoParametro.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevoParametro.setText("Nuevo Parámetro");
        btn_nuevoParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoParametroActionPerformed(evt);
            }
        });

        btn_ModfParam.setBackground(new java.awt.Color(26, 84, 147));
        btn_ModfParam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ModfParam.setForeground(new java.awt.Color(255, 255, 255));
        btn_ModfParam.setText("Modificar Parámetro");
        btn_ModfParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModfParamActionPerformed(evt);
            }
        });

        btn_ElimParam.setBackground(new java.awt.Color(26, 84, 147));
        btn_ElimParam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ElimParam.setForeground(new java.awt.Color(255, 255, 255));
        btn_ElimParam.setText("Eliminar Parámetro");
        btn_ElimParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ElimParamActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(26, 84, 147));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_ppalLayout = new javax.swing.GroupLayout(pnl_ppal);
        pnl_ppal.setLayout(pnl_ppalLayout);
        pnl_ppalLayout.setHorizontalGroup(
            pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ppalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ppalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ppalLayout.createSequentialGroup()
                        .addComponent(btn_nuevoParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_ModfParam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_ElimParam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ppalLayout.createSequentialGroup()
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(pnl_ppalLayout.createSequentialGroup()
                .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ppalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_idParam, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_DescFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_ppalLayout.createSequentialGroup()
                                .addComponent(txt_IdFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_valParam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ValorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_ppalLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnl_ppalLayout.setVerticalGroup(
            pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ppalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idParam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdFiltro)
                    .addComponent(lbl_valParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ValorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DescFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_ppalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevoParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ModfParam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ElimParam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ppal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ppal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IdFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdFiltroActionPerformed

    private void txt_DescFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DescFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescFiltroActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String idParam = this.txt_IdFiltro.getText();
        String valorParam = this.txt_ValorFiltro.getText();
        String descParam = this.txt_DescFiltro.getText();
        List<Parametros> lstParam = null;
        try {
            lstParam = paramDao.consultaParametros(idParam != null ? idParam.toUpperCase() : idParam,
                    valorParam != null ? valorParam.toUpperCase() : valorParam,
                    descParam != null ? descParam.toUpperCase() : descParam);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error consultando Datos: " + e.getMessage(),
                                          "Error en consulta", JOptionPane.ERROR_MESSAGE);
        }
        ParametrosModel model = new ParametrosModel(lstParam);
        tbl_Parametros.setModel(model);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_nuevoParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoParametroActionPerformed
        GestionParametros gp = new GestionParametros(paramDao, this, null, false);
        gp.setVisible(true);
    }//GEN-LAST:event_btn_nuevoParametroActionPerformed

    private void btn_ModfParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModfParamActionPerformed
        int row = this.tbl_Parametros.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar un parametro", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        /*Conviserto el objeto en un parametro, mediante el cast*/
        Parametros tmpParam = (Parametros) this.tbl_Parametros.getValueAt(row, ParametrosModel.OBJECT_COL);
        GestionParametros gp = new GestionParametros(paramDao, this, tmpParam, true);
        gp.setVisible(true);
    }//GEN-LAST:event_btn_ModfParamActionPerformed

    private void btn_ElimParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ElimParamActionPerformed
        try {
            int row = this.tbl_Parametros.getSelectedRow();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Debe Seleccionar un parametro", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int rta = JOptionPane.showConfirmDialog(this, "¿Está seguro de ELIMINAR este parametro?",
                    "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(rta!= JOptionPane.YES_OPTION){
                return;
            }
            Parametros tmpParam = (Parametros) this.tbl_Parametros.getValueAt(row, ParametrosModel.OBJECT_COL);
            paramDao.eliminarParametro(tmpParam);
            refrescarTabla();
            JOptionPane.showMessageDialog(this, "Parametro Eliminado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error eliminando Datos: " + e.getMessage(),
                                          "Error en proceso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ElimParamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.txt_IdFiltro.setText("");
        this.txt_ValorFiltro.setText("");
        this.txt_DescFiltro.setText("");
        this.refrescarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        this.setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_lblHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParametrosPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParametrosPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParametrosPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParametrosPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CSSParser cssParser = new CSSParser();
                String styling =
                   "JButton { foreground: red }"+
                   "JButton#second { font-size: 20pt; foreground: blue }"+
                   "JButton.italic { font-style: italic; foreground: #008000 }";
                Stylesheet stylesheet = cssParser.parse(styling);   
                ParametrosPpal param = new ParametrosPpal();                
                param.setVisible(true);    
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ElimParam;
    private javax.swing.JButton btn_ModfParam;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_nuevoParametro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lbl_idParam;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_valParam;
    private javax.swing.JPanel pnl_ppal;
    private javax.swing.JTable tbl_Parametros;
    private javax.swing.JTextField txt_DescFiltro;
    private javax.swing.JTextField txt_IdFiltro;
    private javax.swing.JTextField txt_ValorFiltro;
    // End of variables declaration//GEN-END:variables
}
